import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState();
  const [dateEvent, setDateEvent] = useState();

  useEffect(() => {
    (async (setLoading, setResult, setDateEvent) => {
      const res = await axios
        .get(`http://localhost:3000/api/hello`)
        .catch((error) => {
          console.error(error);
        });
      const test = new Date(res.data.eventDate);
      const date =
        test.getDate() + "-" + (test.getMonth() + 1) + "-" + test.getFullYear();
      setResult(res.data);
      setDateEvent(date);
      setLoading(false);
    })(setLoading, setResult, setDateEvent);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Gametek Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!loading && (
          <div className={styles.main}>
            <h1 className={styles.title} style={{ fontSize: "2.9rem" }}>
              Découvrez le podium de notre dernier évènement !
            </h1>
            <p className={styles.description}>
              De l'event :
              <code className={styles.code}>{result.eventName}</code>
              qui à eu lieu le
              <code className={styles.code}>{dateEvent}</code>
            </p>
            <div className={styles.grid}>
              <span className={styles.card}>
                <h2>{result.first}</h2>
                <img src="https://img.icons8.com/color/50/000000/first-place-ribbon.png" />
              </span>
              <span className={styles.card}>
                <h2>{result.second}</h2>
                <img src="https://img.icons8.com/color/50/000000/second-place-ribbon.png" />
              </span>
              <span className={styles.card}>
                <h2>{result.third}</h2>
                <img src="https://img.icons8.com/color/50/000000/third-place-ribbon.png" />
              </span>
            </div>
          </div>
        )}
      </main>
      <footer className={styles.footer}>
        <div>Expérience HUB réalisée par Lia Perochaud</div>
      </footer>
    </div>
  );
}
