import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState, useEffect } from 'react';



export default function Home() {
  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState();

  useEffect(() => {
    (async (setLoading, setResult) => {
      const res = await axios.get(`http://localhost:3000/api/hello`).catch(error => {console.error(error)});
      setResult(res);
      setLoading(false);
    })(setLoading, setResult);
  }, []);

const eventName = "Weekly";
const eventDate = "07-11-2020"
const first = "Lia";
const second = "DazzLeCube";
const third = "Sinep";

  return (
    <div className={styles.container}>
      <Head>
        <title>Gametek Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!loading && (
          <div className={styles.main}>
        <h1 className={styles.title} style={{ fontSize: "2.9rem"}}>
          Découvrez le podium de notre dernier évènement !
        </h1>
        <p className={styles.description}>
          De l'event :
          <code className={styles.code}>{eventName}</code>
          qui à eu lieu le
          <code className={styles.code}>{eventDate}</code>
        </p>
        <div className={styles.grid}>
          <span className={styles.card}>
            <h2>{first}</h2>
            <img src="https://img.icons8.com/color/50/000000/first-place-ribbon.png"/>
          </span>
          <span className={styles.card}>
            <h2>{second}</h2>
            <img src="https://img.icons8.com/color/50/000000/second-place-ribbon.png"/>
          </span>
          <span className={styles.card}>
            <h2>{third}</h2>
            <img src="https://img.icons8.com/color/50/000000/third-place-ribbon.png"/>
          </span>
        </div>
        </div>
        )}
      </main>
      <footer className={styles.footer}>
        <span> Expérience HUB réalisée par Lia Perochaud </span>
      </footer>
    </div>
  )
}
